import { StyleSheet } from "react-native";
import { COLORS } from "../../../Colors";

export default StyleSheet.create({
    scrollViewContainer: {
        display: 'flex',
        marginTop: 50,
        with: '100%',
        alignItems: 'center',
        justifyContent: 'center',
        paddingBottom: 80,
    },
    inputText: {
        color: COLORS.Black,
        backgroundColor: COLORS.ComponentBackground,
        textAlign: 'center',
        height: 40,
        width : "90%",
        borderRadius : 10,
        paddingHorizontal: 10,
        marginVertical: 10,
        shadowColor: COLORS.Black,
        shadowOpacity: 0.3,
        shadowOffset: { width: 4, height: 4},
        elevation: 2,
    },
    roleList: {
        marginRight: 10,
        width: "70%",
        display : "flex",
        flexDirection : "row",
    },
    roleContainer: {
        marginTop:20,
        alignItem: 'center',
        width: "90%",
        display : "flex",
        flexDirection : "row",
    },
    addRoleContainer: {
        marginRight: 5,
    },
    addRoleText: {
        backgroundColor: COLORS.TagColor,
        color: COLORS.Black,
        paddingLeft: 20,
        paddingRight: 20,
        paddingBottom: 4,
        paddingTop: 2,    
        borderRadius : 15,
        textAlign : 'center',
    },
    booksContainer: {
        marginTop: 20,
        alignItem: 'center',
        width: "90%",
    },
    textHolder: {
        fontSize: 20,
        fontWeight: '800',
        color: COLORS.ForegroundHolder,
        textAlign: 'left',
        marginBottom: 10,
    },
    button: {
        textAlign: 'center',
		color: COLORS.LightBackgroundColor,
		marginTop: 20,
		height: 50,
		width: 150,
		shadowColor: COLORS.Black,
        shadowOpacity: 0.3,
        shadowOffset: { width: 4, height: 4},
        elevation: 2,
    },
    roleText: {
        backgroundColor: COLORS.TagColor,
        color: COLORS.Black,
        paddingLeft: 7,
        paddingRight: 7,
        paddingBottom: 4,
        paddingTop: 2,    
        borderRadius : 15,
        textAlign : 'center',
    },
});