import { StyleSheet } from "react-native";

export default StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: '#fff',
      alignItems: 'center',
      justifyContent: 'center',
    },
    btnBackground: {
        width: 126,
        height: 34,
        justifyContent: 'center',
        backgroundColor: '#03989E',
        borderRadius: 15,
        transition: 0.2,
    },
    btnText: {
        textAlign: 'center',
        color: '#FFFFFF',
        marginVertical: 8,
    },
    txtFieldBackground: {
        justifyContent: 'center',
        width: 261,
        height: 55,
        margin: 10,
        backgroundColor: '#FFFFFF',
        borderBottomWidth: 2,
        borderBottomColor: '#03989E',
        shadowOffset: {width: 0, height: 4},
        shadowColor: '#FFFFFF',
        shadowOpacity: 0.50,
        shadowRadius: 4,
        borderRadius: 5,
    },
    txtFieldText: {
        textAlign: 'left',
        color: '#ACB3BF',
        width: '100%',
        height: '30%',
        paddingLeft: 8,
        paddingTop: 0,
        fontSize: 13,
        lineHeight: 16,
    },
    txtFieldInput: {
        textAlign: 'left',
        color: '#000000',
        paddingLeft: 8,
        width: '100%',
        height: '70%',
        fontSize: 13,
        lineHeight: 16,
    },
});