import { StyleSheet } from "react-native";

export default StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: '#03989E',
      alignItems: 'center',
      justifyContent: 'center',
    },
    logo: {
        width: '60%',
        height: '30vh',
        position: 'absolute',
        top: 0,
    },
    content : {
        backgroundColor: '#FFFFFF',
        width: '100%',
        position: 'absolute',
        bottom: 0,
        borderTopLeftRadius: 30,
        borderTopRightRadius: 30,
    },
    header: {
        fontSize: 32,
        fontWeight: '800',
        color: '#000000',
        textAlign: 'center',
        flexDirection: 'row',
        justifyContent: 'center',
        alignItems: 'center',
        marginTop: '3vh',
    },
    title: {
        fontSize: 32,
        fontWeight: '800',
        color: '#000000',
        textAlign: 'center',
        paddingHorizontal: '20%',
    },
    btnBackground: {
        width: 126,
        height: 34,
        justifyContent: 'center',
        backgroundColor: '#03989E',
        borderRadius: 15,
        transition: 0.2,
    },
    btnText: {
        textAlign: 'center',
        color: '#FFFFFF',
        marginVertical: 8,
    },
    txtFieldBackground: {
        justifyContent: 'center',
        width: 261,
        height: 55,
        margin: 10,
        backgroundColor: '#FFFFFF',
        borderBottomWidth: 2,
        borderBottomColor: '#03989E',
        shadowOffset: {width: 0, height: 4},
        shadowColor: '#000000',
        shadowOpacity: 0.25,
        shadowRadius: 4,
        borderRadius: 5,
    },
    txtFieldText: {
        textAlign: 'left',
        color: '#ACB3BF',
        width: '100%',
        height: '30%',
        paddingLeft: 8,
        paddingTop: 0,
        fontSize: 13,
        lineHeight: 16,
    },
    txtFieldInput: {
        textAlign: 'left',
        color: '#000000',
        paddingLeft: 8,
        width: '100%',
        height: '70%',
        fontSize: 13,
        lineHeight: 16,
    },
    link: {
        color: '#03989E',
        paddingHorizontal: 5,
    },
    cardBackground: {
        width: "90%",
        height: "20vh",
        backgroundColor: '#FFFFFF',
        borderBottomWidth: 2,
        borderBottomColor: '#EEEEEE',
        shadowOffset: {width: 0, height: 4},
        shadowColor: '#000000',
        shadowOpacity: 0.25,
        shadowRadius: 4,
        borderRadius: 5,
        marginBottom: 30,
    },
    cardUser:{
        fontWeight: 'bold',
        fontSize: 16,
        marginLeft: 20,
        marginTop: 5,
    },
    cardTitle:{
        textDecorationStyle: 'solid',
        textDecorationLine: 'underline',
        fontSize: 16,
        marginLeft: 20,
    },
    cardText:{
        color: '#ACB3BF',
        fontSize: 13,
        textAlign: 'justify',
        marginTop: 5,
        marginBottom: 20,
        marginLeft: 20,
        marginRight: 20,
    },
    moreItemsButton: {
        width: 40,
        height: 34,
        justifyContent: 'center',
        backgroundColor: '#F0F0F0',
        borderRadius: 7,
        transition: 0.2,
        textAlign: 'center',
    },
});